NULL =

TEST_SUPPRESSIONS = $(top_builddir)/build/valgrind-suppressions

perform-memcheck: $(TEST_PROGS) $(TEST_SUPPRESSIONS)
	@make -C $(top_builddir)/build all
	@for test in $(TEST_PROGS); do \
		G_SLICE=always-malloc libtool --mode=execute \
			valgrind --trace-children=no --gen-suppressions=all \
			--suppressions=$(TEST_SUPPRESSIONS) \
			--leak-check=full --show-reachable=yes --num-callers=16 \
			--quiet --error-exitcode=33 \
			$(builddir)/$$test; \
	done
