/*
 * Generated by gdbus-codegen 2.32.0. DO NOT EDIT.
 *
 * The license of this code is the same as for the source it was derived from.
 */

#ifndef __IC_DBUS_GENERATED_H__
#define __IC_DBUS_GENERATED_H__

#include <gio/gio.h>

G_BEGIN_DECLS


/* ------------------------------------------------------------------------ */
/* Declarations for org.freedesktop.IdentityConfig.Provider */

#define IC_DBUS_TYPE_PROVIDER (ic_dbus_provider_get_type ())
#define IC_DBUS_PROVIDER(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), IC_DBUS_TYPE_PROVIDER, IcDbusProvider))
#define IC_DBUS_IS_PROVIDER(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), IC_DBUS_TYPE_PROVIDER))
#define IC_DBUS_PROVIDER_GET_IFACE(o) (G_TYPE_INSTANCE_GET_INTERFACE ((o), IC_DBUS_TYPE_PROVIDER, IcDbusProviderIface))

struct _IcDbusProvider;
typedef struct _IcDbusProvider IcDbusProvider;
typedef struct _IcDbusProviderIface IcDbusProviderIface;

struct _IcDbusProviderIface
{
  GTypeInterface parent_iface;

  void (*diagnostics) (
    IcDbusProvider *object,
    const gchar *arg_data);

  void (*status) (
    IcDbusProvider *object,
    const gchar *arg_message);

};

GType ic_dbus_provider_get_type (void) G_GNUC_CONST;

GDBusInterfaceInfo *ic_dbus_provider_interface_info (void);
guint ic_dbus_provider_override_properties (GObjectClass *klass, guint property_id_begin);


/* D-Bus signal emissions functions: */
void ic_dbus_provider_emit_status (
    IcDbusProvider *object,
    const gchar *arg_message);

void ic_dbus_provider_emit_diagnostics (
    IcDbusProvider *object,
    const gchar *arg_data);



/* ---- */

#define IC_DBUS_TYPE_PROVIDER_PROXY (ic_dbus_provider_proxy_get_type ())
#define IC_DBUS_PROVIDER_PROXY(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), IC_DBUS_TYPE_PROVIDER_PROXY, IcDbusProviderProxy))
#define IC_DBUS_PROVIDER_PROXY_CLASS(k) (G_TYPE_CHECK_CLASS_CAST ((k), IC_DBUS_TYPE_PROVIDER_PROXY, IcDbusProviderProxyClass))
#define IC_DBUS_PROVIDER_PROXY_GET_CLASS(o) (G_TYPE_INSTANCE_GET_CLASS ((o), IC_DBUS_TYPE_PROVIDER_PROXY, IcDbusProviderProxyClass))
#define IC_DBUS_IS_PROVIDER_PROXY(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), IC_DBUS_TYPE_PROVIDER_PROXY))
#define IC_DBUS_IS_PROVIDER_PROXY_CLASS(k) (G_TYPE_CHECK_CLASS_TYPE ((k), IC_DBUS_TYPE_PROVIDER_PROXY))

typedef struct _IcDbusProviderProxy IcDbusProviderProxy;
typedef struct _IcDbusProviderProxyClass IcDbusProviderProxyClass;
typedef struct _IcDbusProviderProxyPrivate IcDbusProviderProxyPrivate;

struct _IcDbusProviderProxy
{
  /*< private >*/
  GDBusProxy parent_instance;
  IcDbusProviderProxyPrivate *priv;
};

struct _IcDbusProviderProxyClass
{
  GDBusProxyClass parent_class;
};

GType ic_dbus_provider_proxy_get_type (void) G_GNUC_CONST;

void ic_dbus_provider_proxy_new (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data);
IcDbusProvider *ic_dbus_provider_proxy_new_finish (
    GAsyncResult        *res,
    GError             **error);
IcDbusProvider *ic_dbus_provider_proxy_new_sync (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error);

void ic_dbus_provider_proxy_new_for_bus (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data);
IcDbusProvider *ic_dbus_provider_proxy_new_for_bus_finish (
    GAsyncResult        *res,
    GError             **error);
IcDbusProvider *ic_dbus_provider_proxy_new_for_bus_sync (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error);


/* ---- */

#define IC_DBUS_TYPE_PROVIDER_SKELETON (ic_dbus_provider_skeleton_get_type ())
#define IC_DBUS_PROVIDER_SKELETON(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), IC_DBUS_TYPE_PROVIDER_SKELETON, IcDbusProviderSkeleton))
#define IC_DBUS_PROVIDER_SKELETON_CLASS(k) (G_TYPE_CHECK_CLASS_CAST ((k), IC_DBUS_TYPE_PROVIDER_SKELETON, IcDbusProviderSkeletonClass))
#define IC_DBUS_PROVIDER_SKELETON_GET_CLASS(o) (G_TYPE_INSTANCE_GET_CLASS ((o), IC_DBUS_TYPE_PROVIDER_SKELETON, IcDbusProviderSkeletonClass))
#define IC_DBUS_IS_PROVIDER_SKELETON(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), IC_DBUS_TYPE_PROVIDER_SKELETON))
#define IC_DBUS_IS_PROVIDER_SKELETON_CLASS(k) (G_TYPE_CHECK_CLASS_TYPE ((k), IC_DBUS_TYPE_PROVIDER_SKELETON))

typedef struct _IcDbusProviderSkeleton IcDbusProviderSkeleton;
typedef struct _IcDbusProviderSkeletonClass IcDbusProviderSkeletonClass;
typedef struct _IcDbusProviderSkeletonPrivate IcDbusProviderSkeletonPrivate;

struct _IcDbusProviderSkeleton
{
  /*< private >*/
  GDBusInterfaceSkeleton parent_instance;
  IcDbusProviderSkeletonPrivate *priv;
};

struct _IcDbusProviderSkeletonClass
{
  GDBusInterfaceSkeletonClass parent_class;
};

GType ic_dbus_provider_skeleton_get_type (void) G_GNUC_CONST;

IcDbusProvider *ic_dbus_provider_skeleton_new (void);


/* ------------------------------------------------------------------------ */
/* Declarations for org.freedesktop.IdentityConfig.Kerberos */

#define IC_DBUS_TYPE_KERBEROS (ic_dbus_kerberos_get_type ())
#define IC_DBUS_KERBEROS(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), IC_DBUS_TYPE_KERBEROS, IcDbusKerberos))
#define IC_DBUS_IS_KERBEROS(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), IC_DBUS_TYPE_KERBEROS))
#define IC_DBUS_KERBEROS_GET_IFACE(o) (G_TYPE_INSTANCE_GET_INTERFACE ((o), IC_DBUS_TYPE_KERBEROS, IcDbusKerberosIface))

struct _IcDbusKerberos;
typedef struct _IcDbusKerberos IcDbusKerberos;
typedef struct _IcDbusKerberosIface IcDbusKerberosIface;

struct _IcDbusKerberosIface
{
  GTypeInterface parent_iface;


  gboolean (*handle_discover_realm) (
    IcDbusKerberos *object,
    GDBusMethodInvocation *invocation,
    const gchar *arg_string);

  gboolean (*handle_enroll_machine_with_kerberos_cache) (
    IcDbusKerberos *object,
    GDBusMethodInvocation *invocation,
    const gchar *arg_realm,
    const gchar *arg_kerberos_cache);

  gboolean (*handle_set_logins_enabled) (
    IcDbusKerberos *object,
    GDBusMethodInvocation *invocation,
    gboolean arg_enabled);

  gboolean (*handle_unenroll_machine_with_kerberos_cache) (
    IcDbusKerberos *object,
    GDBusMethodInvocation *invocation,
    const gchar *arg_realm,
    const gchar *arg_kerberos_cache);

  const gchar *const * (*get_enrolled_realms) (IcDbusKerberos *object);

  gboolean  (*get_logins_enabled) (IcDbusKerberos *object);

  gboolean  (*get_logins_possible) (IcDbusKerberos *object);

};

GType ic_dbus_kerberos_get_type (void) G_GNUC_CONST;

GDBusInterfaceInfo *ic_dbus_kerberos_interface_info (void);
guint ic_dbus_kerberos_override_properties (GObjectClass *klass, guint property_id_begin);


/* D-Bus method call completion functions: */
void ic_dbus_kerberos_complete_discover_realm (
    IcDbusKerberos *object,
    GDBusMethodInvocation *invocation,
    const gchar *realm,
    GVariant *discovered);

void ic_dbus_kerberos_complete_enroll_machine_with_kerberos_cache (
    IcDbusKerberos *object,
    GDBusMethodInvocation *invocation);

void ic_dbus_kerberos_complete_unenroll_machine_with_kerberos_cache (
    IcDbusKerberos *object,
    GDBusMethodInvocation *invocation);

void ic_dbus_kerberos_complete_set_logins_enabled (
    IcDbusKerberos *object,
    GDBusMethodInvocation *invocation);



/* D-Bus method calls: */
void ic_dbus_kerberos_call_discover_realm (
    IcDbusKerberos *proxy,
    const gchar *arg_string,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean ic_dbus_kerberos_call_discover_realm_finish (
    IcDbusKerberos *proxy,
    gchar **out_realm,
    GVariant **out_discovered,
    GAsyncResult *res,
    GError **error);

gboolean ic_dbus_kerberos_call_discover_realm_sync (
    IcDbusKerberos *proxy,
    const gchar *arg_string,
    gchar **out_realm,
    GVariant **out_discovered,
    GCancellable *cancellable,
    GError **error);

void ic_dbus_kerberos_call_enroll_machine_with_kerberos_cache (
    IcDbusKerberos *proxy,
    const gchar *arg_realm,
    const gchar *arg_kerberos_cache,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean ic_dbus_kerberos_call_enroll_machine_with_kerberos_cache_finish (
    IcDbusKerberos *proxy,
    GAsyncResult *res,
    GError **error);

gboolean ic_dbus_kerberos_call_enroll_machine_with_kerberos_cache_sync (
    IcDbusKerberos *proxy,
    const gchar *arg_realm,
    const gchar *arg_kerberos_cache,
    GCancellable *cancellable,
    GError **error);

void ic_dbus_kerberos_call_unenroll_machine_with_kerberos_cache (
    IcDbusKerberos *proxy,
    const gchar *arg_realm,
    const gchar *arg_kerberos_cache,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean ic_dbus_kerberos_call_unenroll_machine_with_kerberos_cache_finish (
    IcDbusKerberos *proxy,
    GAsyncResult *res,
    GError **error);

gboolean ic_dbus_kerberos_call_unenroll_machine_with_kerberos_cache_sync (
    IcDbusKerberos *proxy,
    const gchar *arg_realm,
    const gchar *arg_kerberos_cache,
    GCancellable *cancellable,
    GError **error);

void ic_dbus_kerberos_call_set_logins_enabled (
    IcDbusKerberos *proxy,
    gboolean arg_enabled,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean ic_dbus_kerberos_call_set_logins_enabled_finish (
    IcDbusKerberos *proxy,
    GAsyncResult *res,
    GError **error);

gboolean ic_dbus_kerberos_call_set_logins_enabled_sync (
    IcDbusKerberos *proxy,
    gboolean arg_enabled,
    GCancellable *cancellable,
    GError **error);



/* D-Bus property accessors: */
const gchar *const *ic_dbus_kerberos_get_enrolled_realms (IcDbusKerberos *object);
gchar **ic_dbus_kerberos_dup_enrolled_realms (IcDbusKerberos *object);
void ic_dbus_kerberos_set_enrolled_realms (IcDbusKerberos *object, const gchar *const *value);

gboolean ic_dbus_kerberos_get_logins_possible (IcDbusKerberos *object);
void ic_dbus_kerberos_set_logins_possible (IcDbusKerberos *object, gboolean value);

gboolean ic_dbus_kerberos_get_logins_enabled (IcDbusKerberos *object);
void ic_dbus_kerberos_set_logins_enabled (IcDbusKerberos *object, gboolean value);


/* ---- */

#define IC_DBUS_TYPE_KERBEROS_PROXY (ic_dbus_kerberos_proxy_get_type ())
#define IC_DBUS_KERBEROS_PROXY(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), IC_DBUS_TYPE_KERBEROS_PROXY, IcDbusKerberosProxy))
#define IC_DBUS_KERBEROS_PROXY_CLASS(k) (G_TYPE_CHECK_CLASS_CAST ((k), IC_DBUS_TYPE_KERBEROS_PROXY, IcDbusKerberosProxyClass))
#define IC_DBUS_KERBEROS_PROXY_GET_CLASS(o) (G_TYPE_INSTANCE_GET_CLASS ((o), IC_DBUS_TYPE_KERBEROS_PROXY, IcDbusKerberosProxyClass))
#define IC_DBUS_IS_KERBEROS_PROXY(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), IC_DBUS_TYPE_KERBEROS_PROXY))
#define IC_DBUS_IS_KERBEROS_PROXY_CLASS(k) (G_TYPE_CHECK_CLASS_TYPE ((k), IC_DBUS_TYPE_KERBEROS_PROXY))

typedef struct _IcDbusKerberosProxy IcDbusKerberosProxy;
typedef struct _IcDbusKerberosProxyClass IcDbusKerberosProxyClass;
typedef struct _IcDbusKerberosProxyPrivate IcDbusKerberosProxyPrivate;

struct _IcDbusKerberosProxy
{
  /*< private >*/
  GDBusProxy parent_instance;
  IcDbusKerberosProxyPrivate *priv;
};

struct _IcDbusKerberosProxyClass
{
  GDBusProxyClass parent_class;
};

GType ic_dbus_kerberos_proxy_get_type (void) G_GNUC_CONST;

void ic_dbus_kerberos_proxy_new (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data);
IcDbusKerberos *ic_dbus_kerberos_proxy_new_finish (
    GAsyncResult        *res,
    GError             **error);
IcDbusKerberos *ic_dbus_kerberos_proxy_new_sync (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error);

void ic_dbus_kerberos_proxy_new_for_bus (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data);
IcDbusKerberos *ic_dbus_kerberos_proxy_new_for_bus_finish (
    GAsyncResult        *res,
    GError             **error);
IcDbusKerberos *ic_dbus_kerberos_proxy_new_for_bus_sync (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error);


/* ---- */

#define IC_DBUS_TYPE_KERBEROS_SKELETON (ic_dbus_kerberos_skeleton_get_type ())
#define IC_DBUS_KERBEROS_SKELETON(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), IC_DBUS_TYPE_KERBEROS_SKELETON, IcDbusKerberosSkeleton))
#define IC_DBUS_KERBEROS_SKELETON_CLASS(k) (G_TYPE_CHECK_CLASS_CAST ((k), IC_DBUS_TYPE_KERBEROS_SKELETON, IcDbusKerberosSkeletonClass))
#define IC_DBUS_KERBEROS_SKELETON_GET_CLASS(o) (G_TYPE_INSTANCE_GET_CLASS ((o), IC_DBUS_TYPE_KERBEROS_SKELETON, IcDbusKerberosSkeletonClass))
#define IC_DBUS_IS_KERBEROS_SKELETON(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), IC_DBUS_TYPE_KERBEROS_SKELETON))
#define IC_DBUS_IS_KERBEROS_SKELETON_CLASS(k) (G_TYPE_CHECK_CLASS_TYPE ((k), IC_DBUS_TYPE_KERBEROS_SKELETON))

typedef struct _IcDbusKerberosSkeleton IcDbusKerberosSkeleton;
typedef struct _IcDbusKerberosSkeletonClass IcDbusKerberosSkeletonClass;
typedef struct _IcDbusKerberosSkeletonPrivate IcDbusKerberosSkeletonPrivate;

struct _IcDbusKerberosSkeleton
{
  /*< private >*/
  GDBusInterfaceSkeleton parent_instance;
  IcDbusKerberosSkeletonPrivate *priv;
};

struct _IcDbusKerberosSkeletonClass
{
  GDBusInterfaceSkeletonClass parent_class;
};

GType ic_dbus_kerberos_skeleton_get_type (void) G_GNUC_CONST;

IcDbusKerberos *ic_dbus_kerberos_skeleton_new (void);


G_END_DECLS

#endif /* __IC_DBUS_GENERATED_H__ */
