'\" t
.\"     Title: realm
.\"    Author: Stef Walter <stef@thewalter.net>
.\" Generator: DocBook XSL Stylesheets v1.76.1 <http://docbook.sf.net/>
.\"      Date: 09/21/2012
.\"    Manual: User Commands
.\"    Source: realmd
.\"  Language: English
.\"
.TH "REALM" "1" "" "realmd" "User Commands"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
realm \- Manage enrollment in realms
.SH "SYNOPSIS"
.HP \w'\fBrealm\ discover\ \fR\fB\-v\fR\fB\ \fR\fB[realm\-name]\fR\ 'u
\fBrealm discover \fR\fB\-v\fR\fB \fR\fB[realm\-name]\fR
.HP \w'\fBrealm\ join\ \fR\fB\-v\fR\fB\ \fR\fB[\-U\ user]\fR\fB\ \fR\fB[realm\-name]\fR\ 'u
\fBrealm join \fR\fB\-v\fR\fB \fR\fB[\-U\ user]\fR\fB \fR\fB[realm\-name]\fR
.HP \w'\fBrealm\ leave\ \fR\fB\-v\fR\fB\ \fR\fB[\-U\ user]\fR\fB\ \fR\fB[realm\-name]\fR\ 'u
\fBrealm leave \fR\fB\-v\fR\fB \fR\fB[\-U\ user]\fR\fB \fR\fB[realm\-name]\fR
.HP \w'\fBrealm\ list\fR\ 'u
\fBrealm list\fR
.HP \w'\fBrealm\ permit\ \fR\fB[\-a]\fR\fB\ \fR\fB[\-R\ realm]\fR\fB\ \fR\fB{user}\fR\fB\ \&.\&.\&.\fR\ 'u
\fBrealm permit \fR\fB[\-a]\fR\fB \fR\fB[\-R\ realm]\fR\fB \fR\fB{user}\fR\fB \&.\&.\&.\fR
.HP \w'\fBrealm\ deny\ \fR\fB[\-a]\fR\fB\ \fR\fB[\-R\ realm]\fR\fB\ \fR\fB{user}\fR\fB\ \&.\&.\&.\fR\ 'u
\fBrealm deny \fR\fB[\-a]\fR\fB \fR\fB[\-R\ realm]\fR\fB \fR\fB{user}\fR\fB \&.\&.\&.\fR
.SH "DESCRIPTION"
.PP
\fBrealm\fR
is a command line tool that can be used to manage enrollment in kerberos realms, like Active Directory domains or IPA domains\&.
.SH "DISCOVER"
.PP
Discover a realm and its capabilities\&.
.sp
.if n \{\
.RS 4
.\}
.nf
$ realm discover
.fi
.if n \{\
.RE
.\}
.sp
.if n \{\
.RS 4
.\}
.nf
$ realm discover domain\&.example\&.com
.fi
.if n \{\
.RE
.\}
.PP
After discovering a realm, its name, type and capabilities are displayed\&.
.PP
If no domain is specified, then the domain assigned through DHCP is used as a default\&.
.PP
The following options can be used:
.PP
\fB\-\-client\-software=xxx\fR
.RS 4
Only discover realms for which we can use the given client software\&. Possible values include
\fIsssd\fR
or
\fIwinbind\fR\&.
.RE
.PP
\fB\-\-server\-software=xxx\fR
.RS 4
Only discover realms for run the given server software\&. Possible values include
\fIactive\-directory\fR
or
\fIfreeipa\fR\&.
.RE
.PP
\fB\-\-verbose, \-v\fR
.RS 4
Display verbose diagnostics while doing the discovery\&.
.RE
.SH "JOIN"
.PP
Configure the local machine for use with a realm\&.
.sp
.if n \{\
.RS 4
.\}
.nf
$ realm join domain\&.example\&.com
.fi
.if n \{\
.RE
.\}
.sp
.if n \{\
.RS 4
.\}
.nf
$ realm join \-user=admin \-\-computer\-ou=OU=Special domain\&.example\&.com
.fi
.if n \{\
.RE
.\}
.PP
The realm is first discovered, as we would with the
\fBdiscover\fR
command\&. If no domain is specified, then the domain assigned through DHCP is used as a default\&.
.PP
After a successful join, the computer will be in a state where it is able to resolve remote user and group names from the realm\&. For kerberos realms, a computer account and host keytab is created\&.
.PP
Joining arbitrary kerberos realms is not supported\&. The realm must have a supported mechanism for joining from a client machine, such as Active Directory or FreeIPA\&.
.PP
Unless a
[\-\-user]
is explicitly specified, then if possible, an automatic join is attempted first\&.
.PP
The following options can be used:
.PP
\fB\-\-client\-software=xxx\fR
.RS 4
Only join realms for which we can use the given client software\&. Possible values include
\fIsssd\fR
or
\fIwinbind\fR\&. Not all values are supported for all realms\&. By default the client software is automatically selected\&.
.RE
.PP
\fB\-\-computer\-ou=OU=xxx\fR
.RS 4
The distinguished name of an organizational unit to create the computer account\&. The exact format of the distinguished name depends on the client software and membership software\&. You can usually omit the root DSE portion of distinguished name\&.
.RE
.PP
\fB\-\-membership\-software=xxx\fR
.RS 4
The software to use when joining to the realm\&. Possible values include
\fIsamba\fR
or
\fIadcli\fR\&. Not all values are supported for all realms\&. By default the membership software is automatically selected\&.
.RE
.PP
\fB\-\-one\-time\-password=xxxx\fR
.RS 4
Perform the join using a one time password specified on the command line\&. This is not possible with all types of realms\&.
.RE
.PP
\fB\-\-server\-software=xxx\fR
.RS 4
Only join realms for run the given server software\&. Possible values include
\fIactive\-directory\fR
or
\fIfreeipa\fR\&.
.RE
.PP
\fB\-\-user\fR
.RS 4
The user name to be used to authenticate with when joining the machine to the realm\&. You will be prompted for a password\&.
.RE
.PP
\fB\-\-verbose, \-v\fR
.RS 4
Display verbose diagnostics while doing the discovery and join\&.
.RE
.SH "LEAVE"
.PP
Deconfigure the local machine for use with a realm\&.
.sp
.if n \{\
.RS 4
.\}
.nf
$ realm leave
.fi
.if n \{\
.RE
.\}
.sp
.if n \{\
.RS 4
.\}
.nf
$ realm leave domain\&.example\&.com
.fi
.if n \{\
.RE
.\}
.PP
If no realm name is specified, then the first configured realm will be used\&.
.PP
The following options can be used:
.PP
\fB\-\-user\fR
.RS 4
The user name to be used to authenticate with when leaving the realm\&. You will be prompted for a password\&.
.RE
.PP
\fB\-\-verbose, \-v\fR
.RS 4
Display verbose diagnostics while doing the leave operation\&.
.RE
.SH "LIST"
.PP
List all the discovered and configured realms\&.
.sp
.if n \{\
.RS 4
.\}
.nf
$ realm list
.fi
.if n \{\
.RE
.\}
.PP
The following options can be used:
.PP
\fB\-\-verbose, \-v\fR
.RS 4
Display verbose diagnostics while listing\&.
.RE
.SH "PERMIT"
.PP
Permit local login by users of the realm\&.
.sp
.if n \{\
.RS 4
.\}
.nf
$ realm permit \-a
.fi
.if n \{\
.RE
.\}
.sp
.if n \{\
.RS 4
.\}
.nf
$ realm permit DOMAIN\eUser
.fi
.if n \{\
.RE
.\}
.PP
If more than one realm is configured, then use the
\fB\-\-realm\fR
option to specify which realm to permit the users on\&.
.PP
The format of the user name can be seen by using the
\fBlist\fR
command\&.
.PP
The following options can be used:
.PP
\fB\-\-all, \-a\fR
.RS 4
Permit login by any valid user of the realm\&.
.RE
.PP
\fB\-\-realm, \-R\fR
.RS 4
Specify the name of the realm to permit users to log into\&.
.RE
.PP
\fB\-\-verbose, \-v\fR
.RS 4
Display verbose diagnostics while doing the operation\&.
.RE
.SH "DENY"
.PP
Deny local login by users of the realm\&.
.sp
.if n \{\
.RS 4
.\}
.nf
$ realm deny \-a
.fi
.if n \{\
.RE
.\}
.sp
.if n \{\
.RS 4
.\}
.nf
$ realm deny DOMAIN\eUser
.fi
.if n \{\
.RE
.\}
.PP
If more than one realm is configured, then use the
\fB\-\-realm\fR
option to specify which realm to deny the users\*(Aq login via\&.
.PP
The format of the user name can be seen by using the
\fBlist\fR
command\&.
.PP
The following options can be used:
.PP
\fB\-\-all, \-a\fR
.RS 4
Deny login by any validuser of the realm\&.
.RE
.PP
\fB\-\-realm, \-R\fR
.RS 4
Specify the name of the realm to deny users login to\&.
.RE
.PP
\fB\-\-verbose, \-v\fR
.RS 4
Display verbose diagnostics while doing the operation\&.
.RE
